import {stubString} from 'lodash';
import {useTranslation} from 'react-i18next';

export const useString = () => {
  return {
    welcome_back: 'Welcome Back!',
    enter_your_email_and_password_to_login:
      'Enter your email and password to login',
    email_or_mobile_number: 'Email/ Mobile No',
    enter_email_or_mobile_number: 'Enter Email/ Mobile No',
    password: 'Password',
    enter_password: 'Enter Password',
    forgot_password: 'Forgot Password?',
    login: 'Login',
    dont_have_an_account: "Don't have an account? ",
    sign_up: 'Sign Up',
    please_enter_your_email: 'Please enter your email',
    please_enter_your_password: 'Please enter your password',
    please_enter_your_name: 'Please enter your name',
    please_enter_your_mobile_number: 'Please enter your mobile number',
    create_account: 'Create Account',
    already_have_an_account: 'Already have an account? ',
    reset_password: 'Reset Password',
    welcome_to_coudpouss: 'Welcome to CoudPouss',
    Search: 'Search ',
    Valuation: 'Valuation',
    JobDate: 'Job Date',
    JobTime: 'Job Time ',
    Home: 'Home',
    Request: 'Request',
    Chat: 'Chat',
    Profile: 'Profile',
    explore_all_service: 'Explore All Services',
    Youhavenotcreatedanyrequest:
      'You have not created any request, please\ncreate a request',
    Requestaservice: 'Request a service',
    Back: 'Back',
    Next: 'Next',
    select_your_service_provider: 'Select Your Service Provider',
    service_provider_message:
      'To get started, please select a category. This will ensure we match you with the most suitable professional for your requirements.',
    Professional: 'Professional',
    Nonprofessional: 'Non-professional',
    SelectACategory: 'Select A Category ',
    category_message:
      'Please pick a category to begin. This will help us connect you with the right professional for your needs.',
    Selectacategory: 'Select a category',
    enter_your_registered_email_or_phone_number_below_to_get_reset_your_password:
      'Enter your Registered Email or Phone Number below to get reset your password.',
    continue: 'Continue',
    To_reset_your_password_Please_enter_the_4_Digit_PIN_sent_to_your_Email_or_Phone_Number:
      'To reset your password. Please enter the 4 Digit PIN sent to your Email',
    code: 'Code',
    resend_code: 'Resend code',
    Your_new_password_must_be_different_from_previously_used_passwords:
      'Your new password must be different from previously used passwords',
    enter_new_password: 'Enter Password',
    re_enter_new_password: 'Re-enter Password',
    set_new_password: 'Set New Password',
    coudPouss: 'CoudPouss',
    Empowering_seniors_with_easy_access_to_trusted_help_care_and_companionship_whenever_needed:
      'Empowering seniors with easy access to trusted help, care, and companionship whenever needed.',
    Sign_up_as_Elder: 'Sign up as Elder',
    Sign_up_as_Professional: 'Sign up as Professional',
    or: 'OR',
    get_started_now: 'Get Started Now',
    log_in: 'Log In',
    enter_OTP: 'Enter OTP',
    verify_OTP: 'Verify OTP',
    create_password: 'Create Password',
    create_a_strong_password: 'Create a strong password',
    next: 'Next',
    confirm_password: 'Confirm Password',
    add_personal_details: 'Add Personal Details',
    enter_profile_details: 'Enter profile details',
    name: 'Name',
    enter_name: 'Enter Name',
    mobile_no: 'Mobile No.',
    enter_mobile_no: 'Enter Mobile No.',
    email: 'Email',
    enter_email: 'Enter Email',
    bc: 'BC',
    upload_profile_picture: 'Upload profile picture',
    address: 'Address',
    enter_address: 'Enter Address',
    choose_your_subscription: 'Choose your subscription',
    select_the_plan_that_fits_your_activity_You_can_change_it_later_in_your_profile:
      'Select the plan that fits your activity. You can change it later in your profile.',
    professional_certified: 'Professional (Certified)',
    subscribe: 'Subscribe',
    skip: 'Skip',
    monthly: 'Monthly',
    billed_recurring_monthly_cancel_anytime:
      '*Billed & recurring monthly cancel anytime',
    non_certified_provider: 'Non-Certified Provider',
    all_premium_plans: 'All Premium Plans',
    subscribe_text:
      'Your membership starts as soon as you set up payment and subscribe. Your monthly charge will occur on the last day of the current billing period. We’ll renew your membership for you can manage your subscription or turn off auto-renewal under accounts setting.\n\nBy continuing, you are agreeing to these terms. See the privacy statement and restricions.',
    please_select_a_plan: 'Please select a plan',
    selected_plan_details: 'Selected Plan Details',
    start_your_journey_today_first_month_on_Us:
      'Start Your Journey Today –\nFirst Month on Us!',
    subscription_details_text:
      'Subscribe now and enjoy your first month completely free. No payment today – your subscription will start immediately, and you’ll be charged only after 30 days.',
    earn_money_through_coudPouss_secure_escrow_payments:
      'Earn money through CoudPouss (secure escrow payments)',
    certified_badge_visible_to_all_clients:
      'Certified Badge visible to all clients',
    includes_1_service_category_1_per_extra_category:
      'Includes 1 service category, +€1 per extra category',
    subscription_billed_via_Bank_Card_Google_Pay_or_Apple_Pay:
      'Subscription billed via Bank Card, Google Pay, or Apple Pay',
    profile_reviewed_within_72_hours_by_an_administrator:
      'Profile reviewed within 72 hours by an administrator',
    back: 'Back',
    payment_method: 'Payment Method',
    select_a_quick_and_secure_way_to_complete_your_subscription:
      'Select a quick and secure way to complete your subscription.',
    proceed_to_pay: 'Proceed to Pay',
    cancel: 'Cancel',
    choose_payment_method: 'Choose payment method',
    complete_profile_now: 'Complete Profile Now',
    subscription_successful: 'Subscription Successful',
    welcome_aboard_your_subscription_is_now_active_you_can_start_exploring_all_features_immediately:
      'Welcome aboard! Your subscription is now active. You can start exploring all features immediately.',
    subcription_details: 'Subcription Details',
    plan: 'Plan',
    mode_of_payment: 'Mode of Payment',
    transaction_id: 'Transaction ID',
    start_date: 'Start Date',
    billing_cycle: 'Billing Cycle',
    first_charge_date: 'First Charge Date',
    info: 'Info',
    no_paymentwas_taken_today_your_first_month_is_free:
      'No payment was taken today – your first month is free.',
    upload_the_required_documents_to_complete_your_profile_and_gain_the_Certified_badge:
      'Upload the required documents to complete your profile and gain the Certified badge.',
    upload_from_device: 'upload from device',
    a_copy_of_ID: 'A copy of ID',
    kbis_extract: 'Kbis Extract',
    proof_of_residence: 'Proof of residence',
    less_than_3_months_old_e_g_water_or_electricity_bill:
      '*less than 3 months old (e.g., water or electricity bill)',
    additional_details: 'Additional Details',
    years_of_experience: 'Years of Experience',
    tell_us_more_about_your_professional_background_Enter_your_years_of_experience_to_showcase_your_expertise:
      'Tell us more about your professional background. Enter your years of experience to showcase your expertise.',
    experience: 'Experience',
    add_services: 'Add Services',
    select_a_category: 'Select A Category',
    choose_a_category_that_best_matches_your_services_This_helps_us_connect_you_with_the_right_clients:
      'Choose a category that best matches your services. This helps us connect you with the right clients.',
    select_category: 'Select a category',
    select_a_service: 'Select A Service',
    thank_you_for_choosing_a_category_Now_select_the_services_you_want_to_provide_within_this_category:
      'Thank you for choosing a category. Now, select the services you want to provide within this category',
    add_bank_details: 'Add Bank Details',
    account_holder_name: 'Account Holder Name',
    account_number: 'Account Number',
    bank_name: 'Bank Name',
    ifsc_code: 'IFSC Code',
    enter_bank_name: 'Enter Bank Name',
    enter_account_number: 'Enter Account Number',
    enter_ifsc_code: 'Enter IFSC Code',
    confirm_account_number: 'Confirm Account Number',
    re_enter_account_number: 'Re-enter Account Number',
    add: 'Add',
    review_your_selected_services_You_can_go_back_to_make_changes_or_continue_to_confirm_your_choices:
      'Review your selected services. You can go back to make changes or continue to confirm your choices.',
    great_job_Your_account_is_now_created_successfully:
      'Great job! Your account is now created successfully.',
    SelectAService: 'Select A Service',
    serviceMessage:
      'Thank you for choosing a category. Please select a service so we can provide you with the right support.',
    Choose_a_Service: 'Choose a Service',
    DescribeAboutService: 'Describe About Service',
    barter_product_details: 'Barter Product Details',
    descriptionMessage:
      'Great job! You’ve selected your service. Now, please describe what you need so the professional can understand your request better.',
    EnterServicedescription: 'Enter Service description ',
    Enterdescriptionhere: 'Enter description here...',
    UploadPhotosofaJob: 'Upload Photos of a Job',
    uploadfromdevice: 'upload from device',
    upload_message:
      'Please upload photos of the job so the worker can understand the task better. ',
    ValuationofJob: 'Valuation of Job',
    valuation_message:
      'Great, you’re almost done. Please add the job\nvaluation.',
    EnterValuation: 'Enter Valuation',
    ChooseDate: 'Choose Date',
    ChooseTime: 'Choose Time',
    Sendamessagehere: 'Send a message here...',
    unknown_user: 'Unknown user',
    no_messages_yet: 'No messages yet',
    no_conversations_found: 'No conversations found',
    Preview: 'Preview',
    Preview_message:
      'Well done! You’ve completed all the steps. Please review the preview and edit any details if needed.',
    JobDetails: 'Job Details',
    Servicedescription: 'Service description',
    Jobphotos: 'Job photos',
    ViewQuote: 'View Quote',
    QuoteAmount: 'Quote Amount',
    Negotiate: 'Negotiate',
    Aboutprofessional: 'About professional',
    ViewProfile: 'View Profile',
    Personalizedshortmessage: 'Personalized short message',
    Supportingdocuments: 'Supporting documents',
    ViewDocument: 'View Document',
    Shortvideos: 'Short videos',
    Reject: 'Reject',
    Accept: 'Accept',
    Overallrating: 'Overall rating',
    Certified: 'Certified',
    Clients: 'Clients',
    Bio: 'Bio',
    ExperienceSpecialities: 'Experience & Specialities',
    ReadLess: 'Read Less',
    ReadMore: 'Read More',
    Achievements: 'Achievements',
    Photosofpastwork: 'Photos of past work',
    CustomerRatings: 'Customer Ratings',
    RecentWorksReviews: 'Recent Works & Reviews',
    RejectServicerequest: 'Reject Service request',
    Pricehigherthancompetitors: 'Price higher than competitors',
    Lateresponse: 'Late response',
    Rejectedforanotherreason: 'Rejected for another reason',
    Cancel: 'Cancel',
    ConfirmServicerequest: 'Confirm Service request ?',
    No: 'No',
    Yes: 'Yes',
    Proceedtopayment: 'Proceed to payment',
    payment_message:
      'Once the payment is done, the funds will be held securely in escrow. After the service is rendered, the payment will be released to the provider upon entering the security code',
    FinalPaymentBreakdown: 'Final Payment Breakdown',
    FinalizedQuoteAmount: 'Finalized Quote Amount ',
    PlatformFee: 'Platform Fee',
    Taxes: 'Taxes',
    Total: 'Total',
    ProceedtoPay: 'Proceed to Pay',
    ServiceConfirmed: 'Service Confirmed',
    service_confirmed_message:
      'Your service has been successfully confirmed with the expert. Here are the payment and service details. ',
    Trackservice: 'Track service',
    TaskDetails: 'Task Details',
    SecurityCode: 'Security Code',
    security_note: 'Note: Final 3 digits will be given to you on service date',
    CheckStatus: 'Check Status',
    WriteaReview: 'Write a Review',
    LeaveaReview: 'Leave a Review',
    reviewMessage: 'We greatly value your feedback',
    reviewQuestion: 'How do you rate Bessie Cooper?',
    OverallService: 'Overall Service',
    Reliability: 'Reliability',
    Punctuality: 'Punctuality',
    Solution: 'Solution',
    Payout: 'Payout',
    Pleaseshareyourexperience: 'Please share your experience',
    Writeyourreviewhere: 'Write your review here…',
    Submit: 'Submit',
    TaskStatus: 'Task Status',
    Transport: 'Transport',
    PersonalCare: 'Personal Care',
    TechSupport: 'Tech Support',
    ResentRequests: 'Resent Requests',
    ViewAll: 'View All',
    FavoriteProfessionals: 'Favorite Professionals',
    ExploreServiceRequests: 'Explore Service Requests',
    EstimatedCost: 'Estimated Cost',
    Quote: 'Quote',
    RecentTasks: 'Recent Tasks',
    ServicePreview: 'Service Preview',
    Aboutclient: 'About client',
    Addquoteamount: 'Add quote amount',
    EnterQuoteAmount: 'Enter Quote Amount',
    Addpersonalizedshortmessage: 'Add personalized short message',
    Attachsupportingdocuments: 'Attach supporting documents',
    Uploadashortvideo: ' Upload a short video (max 2 minutes)',
    SubmitQuote: 'Submit Quote',
    manage_services: 'Manage Services',
    manage_subscription: 'Manage Subscription',
    account_under_verification: 'Account under verification',
    check_status: 'Check Status',
    about_me: 'About Me',
    edit_profile: 'Edit Profile',
    upload_images_of_past_works: 'Upload images of past works',
    public_profile_details: 'Public profile Details',
    application_status: 'Application Status',
    unfortunately_your_application_could_not_be_approved_due_to_missing_or_invalid_documents:
      'Unfortunately, your application could not be approved due to missing or invalid documents.',
    upload_documents: 'Upload Documents',
    upload: 'Upload',
    documents_uploaded_successfully_your_documents_will_be_reviewed_within_72_hours:
      'Documents uploaded successfully. Your documents will be reviewed within 72 hours.',
    proceed: 'Proceed',
    here_you_can_easily_manage_your_service_categories_each_additional_category_you_add_will_incur_a_monthly_fee_of:
      'Here, you can easily manage your service categories. Each additional category you add will incur a monthly fee of €1.',
    add_more_services: 'Add more services',
    additional_category_you_add_will_incur_a_monthly_fee_of:
      'Additional category you add will incur a monthly fee of €1.',
    you_are_on_Non_professional_plan_that_s_why_you_need_to_pay_to_add_more_category_of_services:
      'You are on Non-professional plan, that’s why you need to pay €1 to add more category of services',
    available_balance: 'Available Balance',
    latest_transactions: 'Latest Transactions',
    request_withdrawal: 'Request Withdrawal',
    bank_details: 'Bank Details',
    primary_bank_account_details: 'Primary Bank Account Details',
    edit_bank_details: 'Edit Bank Details',
    save: 'Save',
    withdraw_history: 'Withdraw History',
    money_withdrawal: 'Money Withdrawal',
    funds_transfer: 'Funds Transfer',
    specify_amount_to_transfer: 'Specify amount to transfer',
    transfer_to: 'Transfer to',
    select_payment_method: 'Select payment method',
    savings_account: 'Savings Account',
    google_pay: 'Google Pay',
    withdrawal_completed_successfully: 'Withdrawal completed\nsuccessfully!',
    active_Plan: 'Active Plan',
    manage_plan: 'Manage Plan',
    next_payment: 'Next Payment',
    non_certified_provider_details: 'Non-Certified Provider Details',
    service_or_item_exchanges_only: 'Service or item exchanges only',
    No_money_transactions_Barter_only: 'No money transactions (Barter only)',
    my_account: 'My Account',
    logout: 'Log Out',
    my_profile: 'My Profile',
    transactions: 'Transactions',
    ratings_reviews: 'Ratings & Reviews',
    notifications: 'Notifications',
    edit_picture_or_avatar: 'Edit picture or avatar',
    delete_profile: 'Delete Profile',
    personal_information: 'Personal Information',
    full_name: 'Full Name',
    e_mail_id: 'E-mail id',
    mobile_number: 'Mobile Number',
    enter_mobile_number: 'Enter Mobile Number',
    update: 'Update',
    are_you_sure_you_want_to_delete_your_account:
      'Are you sure you want to\ndelete your account?',
    delete_account_message:
      'This action cannot be reversed once your account is deleted. All of your data will be permanently erased. If you proceed, there will be no refunds issued.',
    recent_works_reviews: 'Recent works reviews',
    read_more: 'Read More',
    show_less: 'Show Less',
    my_earnings: 'My Earnings',
    thank_you_for_your_review: 'Thank you for your review!',
    back_to_home: 'Back to Home',
    we_appreciated_you_taking_the_time_to_reflect_on_your_experience:
      'We appreciated you taking the time to reflect on your experience',
    write_your_reason_here: 'Write your reason here…',
    please_enter_your_otp: 'Please enter your OTP',
    please_enter_your_re_enter_password: 'Please enter your re-enter password',
    passwords_do_not_match: 'Passwords do not match',
    please_enter_your_address: 'Please enter your address',
    password_validation_message:
      'Password must be at least 8 characters and include an uppercase letter, a number, and a special character',
    profile_updated_successfully: 'Profile updated successfully',
    add_details_of_the_product_or_thing_you_want_to_offer_in_exchange_for_the_service:
      'Add details of the product or thing you want to offer in exchange for the service.',
    add_product_name: 'Add Product Name',
    upload_photos_of_a_product: 'Upload Photos of a Product',
    quantity: 'Quantity',
    product_images: 'Product Images',
    want_to_add_more_service_categories:
      'Want to add more service\ncategories?',
    view: 'View',
    accept: 'Accept',
    exchange_product: 'Exchange Product',
    what_are_you_looking_for: 'What are you looking for?',
    filters: 'Filters',
    Choose_Date_Time: "Choose Date & Time",
    product: "Product",
    service_cancelled: "Service Cancelled",
    cancelled_message: "This cancellation is happened in less than 48 hours before the scheduled service time. According to policy, your payment will not be fully refunded. A 5% service fee is charged.",
    service_cancelled_message: "Your service has been successfully cancelled. Here are the details regarding your payment and the cancellation policy.",
    service_fee: "Service Fee (5%)",
    cancel_scheduled_service: "Cancel Scheduled Service",
    are_you_sure_you_want_to_cancel_your_scheduled_service_with_the_expert: "Are you sure you want to cancel your scheduled service with the expert?",
    payment_breakdown: "Payment Breakdown",
    confirm_cancellation: "Confirm Cancellation",
    keep_booking: "Keep Booking",
    you_have_not_sent_any_quote_please_sent_a_quotes_to_the_service_request: "You have not sent any quote, please sent\na quotes to the service request",
    you_can_also_upload_a_video: "(You can also upload a video)",
    cancellation_not_possible: "Cancellation not possible",
    are_you_sure_you_want_to_logout: "Are you sure you want to\nlogout?",
    no_data_found: "No data found",
    you_have_not_accepted_any_request_please_accept_a_request: "You have not accepted any request,\nplease accept a request",
    please_enter_your_email_mobile_number: "Please enter your email/ mobile number",
    earnings: "Earnings",
    no_data_available: "No data available",
    no_earnings_this_month: "No earnings for this month",
    no_transactions_data_found: "No transactions data found",
    OutForService: "Out for Service",
    out_for_service_message: "Sharing your location with the client is required to start the service. Would you like to continue?",
    location_permission: "Once you arrive at the specified location shared by the client, you can begin the service.",
    task_status: "Task Status",
    map_view: "Map View",
    we_have_detected_that_you_are_at_your_clients_address_do_you_confirm_the_start_of_the_service: "We have detected that you are at your Client’s address. Do you confirm the start of the service?",
    security_code_text: "Does the provided security code match the one shown below?",
    you_have_not_subscribed_to_any_plan: "You have not subscribed to any plan",
    you_have_already_subscribed_to_a_plan: "You have already subscribed to a plan",
    reached_client_location: "Reached Client Location",
    show_security_code: "Show Security Code",
    the_client_has_confirmed_your_arrival_you_can_now_proceed_to_start_the_service_at_the_specified_location: "The client has confirmed your arrival. You can now proceed to start the service at the specified location.",
    renegotiate: "Renegotiate",
    mark_as_completed: "Mark as Completed",
    renegotiate_message: "If you believe the task is more extensive than planned, you can request a price increase (max +20%)",
    current_payment_breakdown: "Current Payment Breakdown",
    Platform_Fee_15: "Platform Fee (15%)",
    enter_requested_adjustment: "Enter Requested Adjustment",
    Enter_Requested_Adjustment: "Enter Requested Adjustment",
    the_client_has_rejected_your_initial_request_please_resend_it_or_check_your_map_for_accurate_location_detection: "The client has rejected your initial request. Please resend it or check your map for accurate location detection.",
    detect: "Detect",
    resend_request: "Resend Request",
    the_client_has_approved_your_request_Would_you_like_to_proceed_with_the_next_steps: "The client has approved your request. Would you like to proceed with the next steps?",
    enter_security_code: "Enter Security Code",
    enter_security_code_message: "The user will receive the last three digits of the code. Enter these digits provided by the user to validate the service and initiate the process.",
    validate: "Validate",
    security_code_validated_successfully: "Security Code validated successfully.",
    procced_to_payment: "Proceed to Payment",
  };
};

export function getTranslation(str: string) {
  const {t} = useTranslation();
  return t(str);
}
